Etickets/Controllers/ActorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Etickets.Models;
using System.IO;
using System.Data.Entity.Validation;

namespace Etickets.Controllers
{
    public class ActorsController : Controller
    {
        private eTicketsEntities db = new eTicketsEntities();
        [AcceptVerbs(HttpVerbs.Get | HttpVerbs.Post)]
        public ActionResult Index(string searchString)
        {
            if (Session["UserId"] == null)
            {
                // Jika belum login, redirect ke halaman login
                return RedirectToAction("Login", "Users");
            }
             if ((string)Session["UserRole"] != "Admin")
            {
                return RedirectToAction("Index", "Actor");

            }
            var Actors = db.Actors.ToList();
            // Filter movies berdasarkan searchString
            if (!String.IsNullOrEmpty(searchString))
            {
                Actors = Actors.Where(u => u.FullName.Contains(searchString)).ToList();
            }

            return View(Actors);
        }

        // GET: Actors/Details/5
        public ActionResult Details(int? id)
        {
            if (Session["UserId"] == null)
            {
                // Jika belum login, redirect ke halaman login
                return RedirectToAction("Login", "Users");
            }
            if ((string)Session["UserRole"] != "Admin")
            {
                return RedirectToAction("Index", "Actor");

            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Actor actor = db.Actors.Find(id);
            if (actor == null)
            {
                return HttpNotFound();
            }
            return View(actor);
        }

        // GET: Actors/Create
        public ActionResult Create()
        {
            if (Session["UserId"] == null)
            {
                // Jika belum login, redirect ke halaman login
                return RedirectToAction("Login", "Users");
            }
            if ((string)Session["UserRole"] != "Admin")
            {
                return RedirectToAction("Index", "Actor");

            }
            return View();
        }

        // POST: Actors/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Actor actor, HttpPostedFileBase ImageFile)
        {
            if (ModelState.IsValid)
            {
                if (ImageFile != null && ImageFile.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(ImageFile.FileName);
                    var path = Path.Combine(Server.MapPath("~/Content/Images/"), fileName);
                    ImageFile.SaveAs(path);
                    actor.ProfilePictureURL = "~/Content/Images/" + fileName;
                }

                try
                {
                    db.Actors.Add(actor);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (DbEntityValidationException ex)
                {
                    foreach (var error in ex.EntityValidationErrors)
                    {
                        foreach (var validationError in error.ValidationErrors)
                        {
                            ModelState.AddModelError("", "Property: " + validationError.PropertyName + " Error: " + validationError.ErrorMessage);
                        }
                    }
                }
            }

            return View(actor);
        }
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.

        // GET: Actors/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Session["UserId"] == null)
            {
                // Jika belum login, redirect ke halaman login
                return RedirectToAction("Login", "Users");
            }
            if ((string)Session["UserRole"] != "Admin")
            {
                return RedirectToAction("Index", "Actor");

            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Actor actor = db.Actors.Find(id);
            if (actor == null)
            {
                return HttpNotFound();
            }
            return View(actor);
        }

        // POST: Actors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Actor actor, HttpPostedFileBase ImageFile)
        {
            if (ModelState.IsValid)
            {
                if (ImageFile != null && ImageFile.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(ImageFile.FileName);
                    var path = Path.Combine(Server.MapPath("~/Content/Images/"), fileName);
                    ImageFile.SaveAs(path);
                    actor.ProfilePictureURL = "~/Content/Images/" + fileName;
                }

                try
                {
                    db.Entry(actor).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (DbEntityValidationException ex)
                {
                    foreach (var error in ex.EntityValidationErrors)
                    {
                        foreach (var validationError in error.ValidationErrors)
                        {
                            ModelState.AddModelError("", "Property: " + validationError.PropertyName + " Error: " + validationError.ErrorMessage);
                        }
                    }
                }
            }
            return View(actor);
        }

        // GET: Actors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Session["UserId"] == null)
            {
                // Jika belum login, redirect ke halaman login
                return RedirectToAction("Login", "Users");
            }
            if ((string)Session["UserRole"] != "Admin")
            {
                return RedirectToAction("Index", "Actor");

            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Actor actor = db.Actors.Find(id);
            if (actor == null)
            {
                return HttpNotFound();
            }
            return View(actor);
        }

        // POST: Actors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Actor actor = db.Actors.Find(id);
            db.Actors.Remove(actor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Etickets/Controllers/movieController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Etickets.Models;

namespace Etickets.Controllers
{
    public class movieController : Controller
    {
        private eTicketsEntities db = new eTicketsEntities();

        // GET: movie
        public ActionResult Index(string search, int? genre, int page = 1)
        {
            // Check if user is logged in
            if (Session["UserId"] == null)
            {
                return RedirectToAction("Login", "Users");
            }

            // Filter movies by search keyword and/or genre
            var movies = db.movies.AsQueryable();
            if (!string.IsNullOrEmpty(search))
            {
                movies = movies.Where(m => m.Name.Contains(search));
                ViewBag.Search = search;
            }
            if (genre != null)
            {
                movies = movies.Where(m => m.MovieGenres.Any(mg => mg.IdGenre == genre));
                ViewBag.SelectedGenre = genre;
            }

            // Paging
            int pageSize = 3;
            var pagedMovies = movies.Skip((page - 1) * pageSize).Take(pageSize).ToList();
            ViewBag.Page = page;

            // Populate the ViewBag with the list of genres
            ViewBag.Genres = new SelectList(db.Genres, "Id", "Name");

            return View(pagedMovies);
        }





        // GET: movie/Details/5
        public ActionResult Details(int? id)
        {
            if (Session["UserId"] == null)
            {
                // Jika belum login, redirect ke halaman login
                return RedirectToAction("Login", "Users");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            movie movie = db.movies.Find(id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            return View(movie);
        }

        public ActionResult RatingReview(int idMovie)
        {
            if (Session["UserId"] == null)
            {
                // Jika belum login, redirect ke halaman login
                return RedirectToAction("Login", "Users");
            }
            if (idMovie == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var bookingmovie = db.BookingMovies
                                .Where(b => b.IdMovie == idMovie)
                                .ToList();
            var bookings = db.Bookings
                             .Where(b => b.Id == idMovie && b.Rating != null && b.Review != null)
                             .ToList();

            return View(bookings);
        }



        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Etickets/Views/Shared/_Layout.cshtml
@using Etickets.Models

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link rel="shortcut icon" href="~/Content/Images/Etickets.ico" type="image/x-icon" />
     <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <style>
        .search-input {
  width: 200px;
}

        body{
            background-color: #D9D7EF;
        }
        .nav-right {
            float: right;
        }

        .navbar {
            background-color: #403894;
            overflow: hidden;
            position: fixed;
            top: 0;
            width: 100%;
        }

            .navbar a {
                float: left;
                color: #f2f2f2;
                text-align: center;
                padding: 14px 16px;
                text-decoration: none;
                font-size: 14px;
            }

                .navbar a:hover {
                    background-color: #ddd;
                    color: black;
                }

        .active {
            color: white;
        }

        /* Styling for the footer */
        .container-fluid {
  min-height: calc(100vh - 60px); /* 60px adalah tinggi footer */
  position: relative;
  padding-bottom: 60px; /* 60px adalah tinggi footer */
}


        footer {
            background-color: #403894;
            color: #fff;
            padding: 10px;
            text-align: center;
            position: fixed;
            bottom: 0;
            left: 0;
            right: 0;
        }

         .table {
             background-color: white;
    border-collapse: collapse;
    width: 100%;
}

.table th {
    background-color: #f2f2f2;
    color: #333;
    font-weight: bold;
    padding: 10px;
    text-align: left;
}

.table tbody tr:nth-child(even) {
    background-color: #f2f2f2;
}

.table td {
    padding: 10px;
}
.pagination-container {
  display: flex;
  flex-direction: column;
  align-items: center;
}

.pagination {
  display: inline-flex;
  margin-bottom: 10px;
}

.pagination ul {
  display: inline-flex;
  padding-left: 0;
  list-style: none;
}

.pagination li {
  margin-right: 5px;
}

.pagination li a {
  display: block;
  padding: 5px 10px;
  text-decoration: none;
  color: #007bff;
  border: 1px solid #007bff;
  border-radius: 3px;
}

.pagination li.active a {
  background-color: #007bff;
  color: #fff;
}

.pagination li.disabled a {
  color: #868e96;
  border-color: #868e96;
}

.pagination-info {
  display: flex;
  align-items: center;
}

.pagination-info p {
  margin-right: 10px;
  font-size: 14px;
}

.pagination-info form {
  display: flex;
  align-items: center;
}

.pagination-info input[type="number"] {
  width: 50px;
  margin-right: 5px;
  text-align: center;
  font-size: 14px;
  border: 1px solid #ced4da;
  border-radius: 3px;
}

        .pagination-info input[type="submit"] {
            padding: 5px 10px;
            font-size: 14px;
            color: #fff;
            background-color: #007bff;
            border: 1px solid #007bff;
        }
    </style>
    @RenderSection("head", required: false)
</head>
<body>
    <div class="navbar">
        <a href="#">
            <img src="@Url.Content("~/Content/Images/Etickets.jpg")" alt="Etickets Logo" />
        </a>
    @Html.ActionLink("Movie", "Index", "movies", null, new { @class = "nav-link" })
    @Html.ActionLink("Booking", "Index", "Bookings", null, new { @class = "nav-link" })
    @Html.ActionLink("Cinema", "Index", "Cinemas", null, new { @class = "nav-link" })
    @Html.ActionLink("Actor", "Index", "Actors", null, new { @class = "nav-link" })
    @Html.ActionLink("Producer", "Index", "Producers", null, new { @class = "nav-link" })
    @Html.ActionLink("User", "Index", "Users1", null, new { @class = "nav-link" })
    @Html.ActionLink("Genre", "Index", "Genres", null, new { @class = "nav-link" })
    @Html.ActionLink("Movie Actor", "Index", "MovieActors", null, new { @class = "nav-link" })
    @Html.ActionLink("Movie Producer", "Index", "MovieProducers", null, new { @class = "nav-link" })
    @Html.ActionLink("Movie Cinema", "Index", "MovieCinemas", null, new { @class = "nav-link" })
    @Html.ActionLink("Movie Genre", "Index", "MovieGenres", null, new { @class = "nav-link" })
        <div class="nav-right">
            @{
                User user = null;
                if (Session["UserId"] != null)
                {
                    var db = new eTicketsEntities();
                    var userid = Int32.Parse(Session["UserId"].ToString());
                    user = db.Users.Where(w => w.Id == userid).FirstOrDefault();
                }
            }
            @if (user != null)
            {
                <a href="@Url.Action("Details", "Users1", new { id = user.Id })">
                    <img src="@Url.Content(user.ProfilePictureURL??"/")" class="img-fluid rounded-circle" style="border-radius: 50%;" alt="User Profile" width="37" />
                </a>
            }
        </div>


</div>


    <br><br><br><br>
    <div class="container-fluid">
        @RenderBody()
    </div>

    <!-- Footer section -->
    <footer>
        <p>&copy; Ilham Bahri Albi 2023</p>
    </footer>
    <!-- End of footer section -->

    @RenderSection("scripts", required: false)
</body>
</html>

Etickets/Views/Shared/_LayoutUser.cshtml
@using Etickets.Models


<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link rel="shortcut icon" href="~/Content/Images/Etickets.ico" type="image/x-icon" />
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    <style>
        .search-form {
  display: flex;
  align-items: center;
  justify-content: center;
  flex-wrap: wrap;
}

.form-group {
  margin: 10px;
}

label {
  font-weight: bold;
}

input[type="text"], select {
  padding: 10px;
  font-size: 16px;
  border-radius: 5px;
  border: 1px solid #ccc;
  width: 300px;
  max-width: 100%;
  margin-left: 10px;
}

button[type="submit"] {
  padding: 10px 20px;
  font-size: 16px;
  border-radius: 5px;
  background-color: #007bff;
  color: #fff;
  border: none;
  margin-left: 10px;
  cursor: pointer;
}

button[type="submit"]:hover {
  background-color: #0062cc;
}

          .card {
            width: 18rem;
            margin-bottom: 20px;
            border: none;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
        }

        .card-body {
            padding: 1rem;
        }

        .card-img-top {
            object-fit: cover;
            height: 150px;
        }
       body{
            background-color: #D9D7EF;
        }
        

        .nav-right {
            float: right;
        }

        .navbar {
            background-color: #403894;
            overflow: hidden;
            position: fixed;
            top: 0;
            width: 100%;
        }

            .navbar a {
                float: left;
                color: #f2f2f2;
                text-align: center;
                padding: 14px 16px;
                text-decoration: none;
                font-size: 17px;
            }

                .navbar a:hover {
                    background-color: #ddd;
                    color: black;
                }

        .active {
            color: white;
        }

        /* Styling for the footer */
        .container-fluid {
  min-height: calc(100vh - 60px); /* 60px adalah tinggi footer */
  position: relative;
  padding-bottom: 60px; /* 60px adalah tinggi footer */
}


        footer {
            background-color: #403894;
            color: #fff;
            padding: 10px;
            text-align: center;
            position: fixed;
            bottom: 0;
            left: 0;
            right: 0;
        }

         .table {
    border-collapse: collapse;
    width: 100%;
}

.table th {
    background-color: #f2f2f2;
    color: #333;
    font-weight: bold;
    padding: 10px;
    text-align: left;
}

.table tbody tr:nth-child(even) {
    background-color: #f2f2f2;
}

.table td {
    padding: 10px;
}
.pagination-container {
  display: flex;
  flex-direction: column;
  align-items: center;
}

.pagination {
  display: inline-flex;
  margin-bottom: 10px;
}

.pagination ul {
  display: inline-flex;
  padding-left: 0;
  list-style: none;
}

.pagination li {
  margin-right: 5px;
}

.pagination li a {
  display: block;
  padding: 5px 10px;
  text-decoration: none;
  color: #007bff;
  border: 1px solid #007bff;
  border-radius: 3px;
}

.pagination li.active a {
  background-color: #007bff;
  color: #fff;
}

.pagination li.disabled a {
  color: #868e96;
  border-color: #868e96;
}

.pagination-info {
  display: flex;
  align-items: center;
}

.pagination-info p {
  margin-right: 10px;
  font-size: 14px;
}

.pagination-info form {
  display: flex;
  align-items: center;
}

.pagination-info input[type="number"] {
  width: 50px;
  margin-right: 5px;
  text-align: center;
  font-size: 14px;
  border: 1px solid #ced4da;
  border-radius: 3px;
}

        .pagination-info input[type="submit"] {
            padding: 5px 10px;
            font-size: 14px;
            color: #fff;
            background-color: #007bff;
            border: 1px solid #007bff;
        }
    </style>
    @RenderSection("head", required: false)
</head>
<body>
    <div class="navbar">
        <a href="#">
            <img src="@Url.Content("~/Content/Images/Etickets.jpg")" alt="Etickets Logo" />
        </a>
        @Html.ActionLink("Movie", "Index", "movie", null, new { @class = "nav-link" })
        @Html.ActionLink("Booking", "Index", "Booking", null, new { @class = "nav-link" })
        @Html.ActionLink("Cinema", "Index", "Cinema", null, new { @class = "nav-link" })
        @Html.ActionLink("Actor", "Index", "Actor", null, new { @class = "nav-link" })
        @Html.ActionLink("Producer", "Index", "Producer", null, new { @class = "nav-link" })
        <div class="nav-right">
            @{
                User user = null;
                if (Session["UserId"] != null)
                {
                    var db = new eTicketsEntities();
                    var userid = Int32.Parse(Session["UserId"].ToString());
                    user = db.Users.Where(w => w.Id == userid).FirstOrDefault();
                }
            }
            @if (user != null)
            {
                <a href="@Url.Action("Details", "Users", new { id = user.Id })">
                    <img src="@Url.Content(user.ProfilePictureURL??"/")" class="img-fluid rounded-circle" style="border-radius: 50%;" alt="User Profile" width="37" />
                </a>
            }
        </div>


    </div>

    <br />
    <br />

    <div class="container-fluid mt-5">
        @RenderBody()
    </div>

    <!-- Footer section -->
    <footer>
        <p>&copy; Ilham Bahri Albi 2023</p>
    </footer>
    <!-- End of footer section -->

    @RenderSection("scripts", required: false)
</body>
</html>