Etickets/Models/Producer.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etickets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producer()
        {
            this.MovieProducers = new HashSet<MovieProducer>();
        }
    
        public int Id { get; set; }
        public string ProfilePictureURL { get; set; }
        public string FullName { get; set; }
        public string Bio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovieProducer> MovieProducers { get; set; }
    }
}

Etickets/Controllers/ProducerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Etickets.Models;

namespace Etickets.Controllers
{
    public class ProducerController : Controller
    {
        private eTicketsEntities db = new eTicketsEntities();

        // GET: Producer
        public ActionResult Index(string search, int page = 1)
        {
            if (Session["UserId"] == null)
            {
                // Jika belum login, redirect ke halaman login
                return RedirectToAction("Login", "Users");
            }
            var producers = db.Producers.AsQueryable();

            // Filter movies by search keyword
            if (!string.IsNullOrEmpty(search))
            {
                producers = producers.Where(m => m.FullName.Contains(search));
                ViewBag.Search = search;
            }

            // Paging
            int pageSize = 3;
            var pagedproducers = producers.OrderBy(m => m.FullName).Skip((page - 1) * pageSize).Take(pageSize).ToList();
            ViewBag.Page = page;

            return View(pagedproducers);
        }

        // GET: Producer/Details/5
        public ActionResult Details(int? id)
        {
            if (Session["UserId"] == null)
            {
                // Jika belum login, redirect ke halaman login
                return RedirectToAction("Login", "Users");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Producer producer = db.Producers.Find(id);
            if (producer == null)
            {
                return HttpNotFound();
            }
            return View(producer);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Etickets/Controllers/ProducersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Etickets.Models;
using System.Data.Entity.Validation;
using System.IO;

namespace Etickets.Controllers
{
    public class ProducersController : Controller
    {
        private eTicketsEntities db = new eTicketsEntities();
        [AcceptVerbs(HttpVerbs.Get | HttpVerbs.Post)]
        public ActionResult Index(string searchString)
        {
            if (Session["UserId"] == null)
            {
                // Jika belum login, redirect ke halaman login
                return RedirectToAction("Login", "Users");
            }
            if ((string)Session["UserRole"] != "Admin")
            {
                return RedirectToAction("Index", "Producer");
            }

            var Producers = db.Producers.ToList();
            // Filter producers berdasarkan searchString
            if (!String.IsNullOrEmpty(searchString))
            {
                Producers = Producers.Where(u => u.FullName.Contains(searchString)).ToList();
            }

            return View(Producers);
        }

        // GET: Producers/Details/5
        public ActionResult Details(int? id)
        {
            if (Session["UserId"] == null)
            {
                // Jika belum login, redirect ke halaman login
                return RedirectToAction("Login", "Users");
            }
            if ((string)Session["UserRole"] != "Admin")
            {
                return RedirectToAction("Index", "Producer");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Producer producer = db.Producers.Find(id);
            if (producer == null)
            {
                return HttpNotFound();
            }
            return View(producer);
        }

        // GET: Producers/Create
        public ActionResult Create()
        {
            if (Session["UserId"] == null)
            {
                // Jika belum login, redirect ke halaman login
                return RedirectToAction("Login", "Users");
            }
            if ((string)Session["UserRole"] != "Admin")
            {
                return RedirectToAction("Index", "Producer");
            }
            return View();
        }

        // POST: Producers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Producer producer, HttpPostedFileBase ImageFile)
        {
            if (ModelState.IsValid)
            {
                if (ImageFile != null && ImageFile.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(ImageFile.FileName);
                    var path = Path.Combine(Server.MapPath("~/Content/Images/"), fileName);
                    ImageFile.SaveAs(path);
                    producer.ProfilePictureURL = "~/Content/Images/" + fileName;
                }

                try
                {
                    db.Producers.Add(producer);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (DbEntityValidationException ex)
                {
                    foreach (var error in ex.EntityValidationErrors)
                    {
                        foreach (var validationError in error.ValidationErrors)
                        {
                            ModelState.AddModelError("", "Property: " + validationError.PropertyName + " Error: " + validationError.ErrorMessage);
                        }
                    }
                }
            }
            
            return View(producer);
        }
        // GET: Producers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Session["UserId"] == null)
            {
                // Jika belum login, redirect ke halaman login
                return RedirectToAction("Login", "Users");
            }
            if ((string)Session["UserRole"] != "Admin")
            {
                return RedirectToAction("Index", "Producer");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Producer producer = db.Producers.Find(id);
            if (producer == null)
            {
                return HttpNotFound();
            }
            return View(producer);
        }
        
        // POST: Producers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Producer producer, HttpPostedFileBase ImageFile)
        {
            if (ModelState.IsValid)
            {
                if (ImageFile != null && ImageFile.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(ImageFile.FileName);
                    var path = Path.Combine(Server.MapPath("~/Content/Images/"), fileName);
                    ImageFile.SaveAs(path);
                    producer.ProfilePictureURL = "~/Content/Images/" + fileName;
                }

                try
                {
                    db.Entry(producer).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (DbEntityValidationException ex)
                {
                    foreach (var error in ex.EntityValidationErrors)
                    {
                        foreach (var validationError in error.ValidationErrors)
                        {
                            ModelState.AddModelError("", "Property: " + validationError.PropertyName + " Error: " + validationError.ErrorMessage);
                        }
                    }
                }
            }
            return View(producer);
        }
       
        // GET: Producers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Session["UserId"] == null)
            {
                // Jika belum login, redirect ke halaman login
                return RedirectToAction("Login", "Users");
            }
            if ((string)Session["UserRole"] != "Admin")
            {
                return RedirectToAction("Index", "Producer");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Producer producer = db.Producers.Find(id);
            if (producer == null)
            {
                return HttpNotFound();
            }
            return View(producer);
        }

        // POST: Producers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Producer producer = db.Producers.Find(id);
            db.Producers.Remove(producer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Etickets/Views/Producers/Create.cshtml
@model Etickets.Models.Producer

@{
    ViewBag.Title = "Producer";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    
    @using (Html.BeginForm("Create", "Producers", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Producer</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.ProfilePictureURL, "Profile Picture", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" name="ImageFile" id="ImageFile" accept="image/*">
                    @Html.ValidationMessageFor(model => model.ProfilePictureURL, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.FullName, "Full Name", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Bio, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Bio, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Bio, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

Etickets/Views/Producers/Delete.cshtml
@model Etickets.Models.Producer

@{
    ViewBag.Title = "Producer";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Producer</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                Profile Picture
            </dt>
    
            <dd>
                <img src="@Url.Content(Model.ProfilePictureURL??"/")" alt="Movie Image" width="50" />
            </dd>
    
            <dt>
                Full Name
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.FullName)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Bio)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Bio)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>

Etickets/Views/Producers/Details.cshtml
@model Etickets.Models.Producer

@{
    ViewBag.Title = "Producer";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <div>
        <h4>Producer</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                Profile Picture
            </dt>

            <dd>
                <img src="@Url.Content(Model.ProfilePictureURL??"/")" width="50" />
            </dd>
             
            <dt>
               Full Name
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.FullName)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Bio)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Bio)
            </dd>
    
            <dt>
                Movies
            </dt>

            <dd>
                <ul>
                    @*@if (Model.movies != null)
                    {
                        foreach (var movie in Model.movies)
                        {
                            <li>@movie.Name</li>
                        }
                    }
                    else
                    {
                        <li>No movies found.</li>
                    }*@
                </ul>
            </dd>
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>

Etickets/Views/Producers/Edit.cshtml
@model Etickets.Models.Producer

@{
    ViewBag.Title = "Producer";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    
    
    @using (Html.BeginForm("Edit", "Producers", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Producer</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)
            <div class="form-group">
                @Html.LabelFor(model => model.ProfilePictureURL, "Profile Picture", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" name="ImageFile" id="ImageFile" accept="image/*">
                    @Html.ValidationMessageFor(model => model.ProfilePictureURL, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.FullName, "Full Name",  htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Bio, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Bio, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Bio, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

Etickets/Views/Producers/Index.cshtml
@model IEnumerable<Etickets.Models.Producer>

@{
    ViewBag.Title = "Producer";
    Layout = "~/Views/Shared/_Layout.cshtml";

    int totalPages = (int)Math.Ceiling((decimal)Model.Count() / 10);
    int currentPage = ViewBag.PageNumber ?? 1;
    string searchString = ViewBag.SearchString ?? "";
}

    <button class="button-create" onclick="location.href='Producers/Create'">Create</button>
    @using (Html.BeginForm("Index", "Producers", FormMethod.Post))
    {
        <div class="form-group">
            <input type="text" name="searchString" class="form-control search-input" placeholder="Search...">
        </div>
        <button type="submit" class="btn btn-primary">Search</button>
    }
    <table class="table" border="1">
        <tr>
            <th>
                Id
            </th>
            <th>
                Profile Picture
            </th>
            <th>
                Full Name
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Bio)
            </th>
            <th>
                Action
            </th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                <img src="@Url.Content(item.ProfilePictureURL??"/")" alt="Producer Image" width="50" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Bio)
            </td>
            <td>
                <button class="button-edit" onclick="location.href='Producers/Edit?id=@item.Id'">Edit</button>
                <button class="button-details" onclick="location.href='Producers/Details?id=@item.Id'">Details</button>
                <button class="button-delete" onclick="location.href='Producers/Delete?id=@item.Id'">Delete</button>
            </td>
        </tr>
    }
    
    </table>
    <!-- Pagination links -->
    <div class="pagination-container">
        <div class="pagination">
            <ul>
                <li class="previous @(currentPage == 1 ? "disabled" : "")"><a href="@Url.Action("Index", new { pageNumber = currentPage - 1, searchString = searchString })">Prev</a></li>
                @for (int i = 1; i <= totalPages; i++)
                {
                    <li class="@(i == currentPage ? "active" : "")"><a href="@Url.Action("Index", new { pageNumber = i, searchString = searchString })">@i</a></li>
                }
                <li class="next @(currentPage == totalPages ? "disabled" : "")"><a href="@Url.Action("Index", new { pageNumber = currentPage + 1, searchString = searchString })">Next</a></li>
            </ul>
        </div>
        <div class="pagination-info">
            <p>Total Items: @Model.Count()</p>
            <form method="get" action="@Url.Action("Index")">
                <input type="hidden" name="searchString" value="@searchString" />
                <input type="number" name="pageNumber" min="1" max="@totalPages" value="@currentPage" />
                <input type="submit" value="Go" />
            </form>
        </div>
    </div>