Etickets/Controllers/moviesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Etickets.Models;
using System.IO;
using System.Data.Entity.Validation;
using static Etickets.GlobalClass;
using static Etickets.GlobalFunctions;

namespace Etickets.Controllers
{
    public class moviesController : Controller
    {
        private eTicketsEntities db = new eTicketsEntities();

        [AcceptVerbs(HttpVerbs.Get|HttpVerbs.Post)]
        public ActionResult Index(string searchString)
        {
            if (Session["UserId"] == null)
            {
                // Jika belum login atau bukan Admin, redirect ke halaman login
                return RedirectToAction("Login", "Users");
            }

            if ((string)Session["UserRole"] != "Admin")
            {
                return RedirectToAction("Index", "movie");
            }

            IQueryable<movie> movies = db.movies;

            // Filter movies berdasarkan searchString
            if (!String.IsNullOrEmpty(searchString))
            {
                movies = movies.Where(m => m.Name.Contains(searchString));
            }

            return View(movies.ToList());
        }

        public ActionResult Report()
        {
            if (Session["UserId"] == null)
            {
                // Jika belum login atau bukan Admin, redirect ke halaman login
                return RedirectToAction("Login", "Users");
            }

            if ((string)Session["UserRole"] != "Admin")
            {
                return RedirectToAction("Index", "movie");
            }
            
            return View();
        }

        [HttpPost]
        public ActionResult ShowReport(string reporttype)
        {
            var rptfile = "MovieReport"; var rptname = "MovieReport";

            rptfile = rptfile.Replace("PDF", "");


            var sWhere = "WHERE 1=1 ";
            

            var irequest = new ReportRequest()
            {
                rptQuery = "",
                rptFile = rptfile,
                rptPaperSizeEnum = 14,
                rptPaperOrientationEnum = 2,
                rptExportType = reporttype,
                //rptParam = new Dictionary<string, string>()
            };
            //irequest.rptParam.Add("Periode", param.periodstart.ToDateTime().ToString("dd/MM/yyyy") + " - " + param.periodend.ToDateTime().ToString("dd/MM/yyyy"));
            //irequest.rptParam.Add("UserID", Session["UserID"].ToString());
            //irequest.rptParam.Add("sWhere", sWhere);

            var rpt_id = GenerateReport(irequest);

            return Json(new { rptname, rpt_id }, JsonRequestBehavior.AllowGet);
        }

        // GET: movies/Details/5
        public ActionResult Details(int? id)
        {
            if (Session["UserId"] == null)
            {
                // Jika belum login, redirect ke halaman login
                return RedirectToAction("Login", "Users");
            }
            if ((string)Session["UserRole"] != "Admin")
            {
                return RedirectToAction("Index", "movie");

            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            movie movie = db.movies.Find(id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            return View(movie);
        }

        // GET: movies/Create
        public ActionResult Create()
        {
            if (Session["UserId"] == null)
            {
                // Jika belum login, redirect ke halaman login
                return RedirectToAction("Login", "Users");
            }
            if ((string)Session["UserRole"] != "Admin")
            {
                return RedirectToAction("Index", "movie");

            }
            ViewBag.IdActor = new SelectList(db.Actors, "Id", "id");
            ViewBag.IdCinema = new SelectList(db.Cinemas, "Id", "id");
            ViewBag.IdProducer = new SelectList(db.Producers, "Id", "id");
            return View();
        }

        // POST: movies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(movie movie, HttpPostedFileBase ImageFile)
        {
            if (ModelState.IsValid)
            {
                if (ImageFile != null && ImageFile.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(ImageFile.FileName);
                    var path = Path.Combine(Server.MapPath("~/Content/Images/"), fileName);
                    ImageFile.SaveAs(path);
                    movie.ImageURL = "~/Content/Images/" + fileName;
                }

                try
                {
                    db.movies.Add(movie);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (DbEntityValidationException ex)
                {
                    foreach (var error in ex.EntityValidationErrors)
                    {
                        foreach (var validationError in error.ValidationErrors)
                        {
                            ModelState.AddModelError("", "Property: " + validationError.PropertyName + " Error: " + validationError.ErrorMessage);
                        }
                    }
                }
            }

            //ViewBag.IdActor = new SelectList(db.Actors, "Id", "ProfilePictureURL", movie.IdActor);
            //ViewBag.IdCinema = new SelectList(db.Cinemas, "Id", "Logo", movie.IdCinema);
            //ViewBag.IdProducer = new SelectList(db.Producers, "Id", "ProfilePictureURL", movie.IdProducer);
            return View(movie);
        }


        // GET: movies/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Session["UserId"] == null)
            {
                // Jika belum login, redirect ke halaman login
                return RedirectToAction("Login", "Users");
            }
            if ((string)Session["UserRole"] != "Admin")
            {
                return RedirectToAction("Index", "movie");

            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            movie movie = db.movies.Find(id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            //ViewBag.IdActor = new SelectList(db.Actors, "Id", "Id", movie.IdActor);
            //ViewBag.IdCinema = new SelectList(db.Cinemas, "Id", "Id", movie.IdCinema);
            //ViewBag.IdProducer = new SelectList(db.Producers, "Id", "Id", movie.IdProducer);
            return View(movie);
        }

        // POST: movies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(movie movie, HttpPostedFileBase ImageFile)
        {
            if (ModelState.IsValid)
            {
                if (ImageFile != null && ImageFile.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(ImageFile.FileName);
                    var path = Path.Combine(Server.MapPath("~/Content/Images/"), fileName);
                    ImageFile.SaveAs(path);
                    movie.ImageURL = "~/Content/Images/" + fileName;
                }

                try
                {
                    db.Entry(movie).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (DbEntityValidationException ex)
                {
                    foreach (var error in ex.EntityValidationErrors)
                    {
                        foreach (var validationError in error.ValidationErrors)
                        {
                            ModelState.AddModelError("", "Property: " + validationError.PropertyName + " Error: " + validationError.ErrorMessage);
                        }
                    }
                }
            }

            //ViewBag.IdActor = new SelectList(db.Actors, "Id", "ProfilePictureURL", movie.IdActor);
            //ViewBag.IdCinema = new SelectList(db.Cinemas, "Id", "Logo", movie.IdCinema);
            //ViewBag.IdProducer = new SelectList(db.Producers, "Id", "ProfilePictureURL", movie.IdProducer);
            return View(movie);
        }



        // GET: movies/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Session["UserId"] == null)
            {
                // Jika belum login, redirect ke halaman login
                return RedirectToAction("Login", "Users");
            }
            if ((string)Session["UserRole"] != "Admin")
            {
                return RedirectToAction("Index", "movie");

            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            movie movie = db.movies.Find(id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            return View(movie);
        }

        // POST: movies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]

Etickets/Views/movies/Create.cshtml
@model Etickets.Models.movie

@{
    ViewBag.Title = "Movie";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    
    
    @using (Html.BeginForm("Create", "movies", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>movie</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.ImageURL, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" name="ImageFile" id="ImageFile" accept="image/*">
                    @Html.ValidationMessageFor(model => model.ImageURL, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

Etickets/Views/movies/Delete.cshtml
@model Etickets.Models.movie

@{
    ViewBag.Title = "Movie";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>movie</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>
    
            <dt>
                Image
            </dt>
    
            <dd>
                <img src="@Url.Content(Model.ImageURL??"/")" alt="Movie Image" width="50" />
            </dd>
    
 

        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>

Etickets/Views/movies/Details.cshtml
@model Etickets.Models.movie

@{
    ViewBag.Title = "Movie";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var ratings = Model.Bookings.Select(b => b.Rating).ToList(); // get all the ratings for the movie
    double averageRating = ratings.Any() ? Math.Round(ratings.Average().GetValueOrDefault(), 2) : 0;
}

    <div>
        <h4>movie</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>

            <dt>
                Image
            </dt>

            <dd>
                <img src="@Url.Content(Model.ImageURL??"/")" alt="Movie Image" width="50" />
            </dd>

            <dt>
                Actor
            </dt>

            <dd>
                @foreach (var movieActor in Model.MovieActors)
            {
                if (movieActor.IdMovie == Model.Id)
                {
                    var actor = movieActor.Actor;
                        @actor.FullName,
                }
            }
            </dd>

            <dt>
                Cinema
            </dt>

            <dd>
                @foreach (var movieCinema in Model.MovieCinemas)
            {
                if (movieCinema.IdMovie == Model.Id)
                {
                    var actor = movieCinema.Cinema;
                        @actor.Name
                        <br />
                    }
                }
            </dd>

            <dt>
                Producer
            </dt>

            <dd>
                @foreach (var movieProducers in Model.MovieProducers)
            {
                if (movieProducers.IdMovie == Model.Id)
                {
                    var actor = movieProducers.Producer;
                        @actor.FullName
                        <br />
                    }
                }
            </dd>

            <dt>
                Genre
            </dt>

            <dd>
                @foreach (var movieGenres in Model.MovieGenres)
            {
                if (movieGenres.IdMovie == Model.Id)
                {
                    var Genre = movieGenres.Genre;
                        @Genre.Name
                        <br />
                    }
                }
            </dd>

            <dt>
                Average Rating
            </dt>

            <dd>
                @averageRating
            </dd>

        </dl>
        <table class="table" border="1">
            <thead>
                <tr>
                    <th>Time</th>
                    <th>Room</th>
                    <th>Price</th>
            </thead>
            <tbody>
                @foreach (var BookingMovie in Model.BookingMovies)
            {
                if (BookingMovie.IdMovie == Model.Id)
                {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => BookingMovie.Time)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => BookingMovie.Room)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => BookingMovie.Price)
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>

Etickets/Views/movies/Edit.cshtml
@model Etickets.Models.movie

@{
    ViewBag.Title = "Movie";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    
    @using (Html.BeginForm("Edit", "movies", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>movie</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)
    
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>  

            <div class="form-group">
               @Html.LabelFor(model => model.ImageURL, "Image", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" name="ImageFile" id="ImageFile" accept="image/*">
                    @Html.ValidationMessageFor(model => model.ImageURL, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

Etickets/Views/movies/Index.cshtml
@model IEnumerable<Etickets.Models.movie>

@{
    ViewBag.Title = "Movie";
    Layout = "~/Views/Shared/_Layout.cshtml";

    int totalPages = (int)Math.Ceiling((decimal)Model.Count() / 10);
    int currentPage = ViewBag.PageNumber ?? 1;
    string searchString = ViewBag.SearchString ?? "";
}
<p>
<button class="button-report" onclick="location.href='movies/Report'">Report</button>
    <button class="button-create" onclick="location.href='movies/Create'">Create</button>
</p>

@using (Html.BeginForm("Index", "movies", FormMethod.Post))
{
    <div class="form-group">
        <input type="text" name="searchString" class="form-control search-input" placeholder="Search...">
    </div>
    <button type="submit" class="btn btn-primary">Search</button>
}


    <table class="table" border="1">
        <thead>
            <tr>
                <th>
                    Id
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>
                <th>
                    Image
                </th>
                <th>
                    Action             
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                    <img src="@Url.Content(item.ImageURL??"/")" alt="Movie Image" width="50" />
                    </td>
                    <td>
                        <button class="button-edit" onclick="location.href='movies/Edit?id=@item.Id'">Edit</button>
                        <button class="button-details" onclick="location.href='movies/Details?id=@item.Id'">Details</button>
                        <button class="button-delete" onclick="location.href='movies/Delete?id=@item.Id'">Delete</button>
                    </td>
                </tr>
            }
        </tbody>
</table>
<hr />
    <!-- Pagination links -->
    <div class="pagination-container">
        <div class="pagination">
            <ul>
                <li class="previous @(currentPage == 1 ? "disabled" : "")"><a href="@Url.Action("Index", new { pageNumber = currentPage - 1, searchString = searchString })">Prev</a></li>
                @for (int i = 1; i <= totalPages; i++)
                {
                    <li class="@(i == currentPage ? "active" : "")"><a href="@Url.Action("Index", new { pageNumber = i, searchString = searchString })">@i</a></li>
                }
                <li class="next @(currentPage == totalPages ? "disabled" : "")"><a href="@Url.Action("Index", new { pageNumber = currentPage + 1, searchString = searchString })">Next</a></li>
            </ul>
        </div>
        <div class="pagination-info">
            <p>Total Items: @Model.Count()</p>
            <form method="get" action="@Url.Action("Index")">
                <input type="hidden" name="searchString" value="@searchString" />
                <input type="number" name="pageNumber" min="1" max="@totalPages" value="@currentPage" />
                <input type="submit" value="Go" />
            </form>
        </div>
    </div>

Etickets/Views/movies/Report.cshtml

@{
    ViewBag.Title = "Report Movie";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Report Movie</h2>

<div class="text-center">
    <button type="button" id="btnViewReport" class="btn btn-primary btn-md" onclick="ShowReport('')"><b>View Report</b></button>
    <button type="button" id="btnExportPDF" class="btn btn-danger btn-md" onclick="ShowReport('PDF')"><b>Export to PDF</b></button>
    <button type="button" id="btnExportExcel" class="btn btn-success btn-md" onclick="ShowReport('XLS')"><b>Export to Excel</b></button>
    <a href="@Url.Action("Report")" type="button" class="btn btn-default btn-md"><b>Clear</b></a>

    <div class="row">
        <div class="col-md-12">
            <iframe id="ReportFrame" src="" style="border: none; width: 100%; height: 100%;"></iframe>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

<script language="javascript" type="text/javascript">


    $(document).ready(function () {

    })

    function ShowReport(reporttype) {
        //var param = GetFilterData();
        $.ajax({
            url: "@(Url.Action("ShowReport"))",
            data: { reporttype: reporttype },
            cache: false,
            type: "POST",
            success: function (data) {
                $('#ReportFrame').attr("src", "@Url.Content("~/Report/ReportMovie.aspx")" + "?report=" + data.rpt_id + "&rptname=" + data.rptname + "&rpttype=" + reporttype + "");
                //if (reporttype == '')
                   // pleaseWaitDialog.show();
            },
            error: function (err) {
                swal('', err.responseText, 'error');
            }
        });
    }
    $('#ReportFrame').on('load', function () {
        var reportHeight = $("#ReportFrame").contents().find('#CRViewer').height();
        $('#ReportFrame').css('height', (reportHeight + 50) + 'px');
        //pleaseWaitDialog.hide();
    });
</script>